/* This file is autogenerated. DO NOT CHANGE. All changes will be lost */


#include "cloudseal/grpc/cloudseal.qpb.h"

#include <QtProtobuf/qprotobufregistration.h>

#include <cmath>

namespace cloudseal::grpc {

class CloudFile_QtProtobufData : public QSharedData
{
public:
    CloudFile_QtProtobufData()
        : QSharedData(),
          m_size(0)
    {
    }

    CloudFile_QtProtobufData(const CloudFile_QtProtobufData &other)
        : QSharedData(other),
          m_id_proto(other.m_id_proto),
          m_name(other.m_name),
          m_mimeType(other.m_mimeType),
          m_size(other.m_size),
          m_createdTime(other.m_createdTime),
          m_source(other.m_source)
    {
    }

    QString m_id_proto;
    QString m_name;
    QString m_mimeType;
    QtProtobuf::int64 m_size;
    QString m_createdTime;
    QString m_source;
};

CloudFile::~CloudFile() = default;

static constexpr struct {
    QtProtobufPrivate::QProtobufPropertyOrdering::Data data;
    const std::array<uint, 25> qt_protobuf_CloudFile_uint_data;
    const char qt_protobuf_CloudFile_char_data[67];
} qt_protobuf_CloudFile_metadata {
    // data
    {
        0, /* = version */
        6, /* = num fields */
        7, /* = field number offset */
        13, /* = property index offset */
        19, /* = field flags offset */
        24, /* = message full name length */
    },
    // uint_data
    {
        // JSON name offsets:
        25, /* = id */
        28, /* = name */
        33, /* = mimeType */
        42, /* = size */
        47, /* = createdTime */
        59, /* = source */
        66, /* = end-of-string-marker */
        // Field numbers:
        1, /* = id */
        2, /* = name */
        3, /* = mimeType */
        4, /* = size */
        5, /* = createdTime */
        6, /* = source */
        // Property indices:
        0, /* = id */
        1, /* = name */
        2, /* = mimeType */
        3, /* = size */
        4, /* = createdTime */
        5, /* = source */
        // Field flags:
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = id */
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = name */
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = mimeType */
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = size */
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = createdTime */
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = source */
    },
    // char_data
    /* metadata char_data: */
    "cloudseal.grpc.CloudFile\0" /* = full message name */
    /* field char_data: */
    "id\0name\0mimeType\0size\0createdTime\0"
    "source\0"
};

const QtProtobufPrivate::QProtobufPropertyOrdering CloudFile::staticPropertyOrdering = {
    &qt_protobuf_CloudFile_metadata.data
};

void CloudFile::registerTypes()
{
    qRegisterMetaType<CloudFile>();
    qRegisterMetaType<QList<CloudFile>>();
}

CloudFile::CloudFile()
    : QProtobufMessage(&CloudFile::staticMetaObject, &CloudFile::staticPropertyOrdering),
      dptr(new CloudFile_QtProtobufData)
{
}

CloudFile::CloudFile(const CloudFile &other)
    = default;
CloudFile &CloudFile::operator =(const CloudFile &other)
{
    CloudFile temp(other);
    swap(temp);
    return *this;
}
CloudFile::CloudFile(CloudFile &&other) noexcept
    = default;
CloudFile::operator QVariant() const
{
    return QVariant::fromValue(*this);
}
bool comparesEqual(const CloudFile &lhs, const CloudFile &rhs) noexcept
{
    return operator ==(static_cast<const QProtobufMessage&>(lhs),
                       static_cast<const QProtobufMessage&>(rhs))
        && lhs.dptr->m_id_proto == rhs.dptr->m_id_proto
        && lhs.dptr->m_name == rhs.dptr->m_name
        && lhs.dptr->m_mimeType == rhs.dptr->m_mimeType
        && lhs.dptr->m_size == rhs.dptr->m_size
        && lhs.dptr->m_createdTime == rhs.dptr->m_createdTime
        && lhs.dptr->m_source == rhs.dptr->m_source;
}

const QString &CloudFile::id_proto() const &
{
    return dptr->m_id_proto;
}

const QString &CloudFile::name() const &
{
    return dptr->m_name;
}

const QString &CloudFile::mimeType() const &
{
    return dptr->m_mimeType;
}

QtProtobuf::int64 CloudFile::size() const
{
    return dptr->m_size;
}

const QString &CloudFile::createdTime() const &
{
    return dptr->m_createdTime;
}

const QString &CloudFile::source() const &
{
    return dptr->m_source;
}

void CloudFile::setId_proto(const QString &id_proto)
{
    if (dptr->m_id_proto != id_proto) {
        dptr.detach();
        dptr->m_id_proto = id_proto;
    }
}

void CloudFile::setId_proto(QString &&id_proto)
{
    if (dptr->m_id_proto != id_proto) {
        dptr.detach();
        dptr->m_id_proto = std::move(id_proto);
    }
}

void CloudFile::setName(const QString &name)
{
    if (dptr->m_name != name) {
        dptr.detach();
        dptr->m_name = name;
    }
}

void CloudFile::setName(QString &&name)
{
    if (dptr->m_name != name) {
        dptr.detach();
        dptr->m_name = std::move(name);
    }
}

void CloudFile::setMimeType(const QString &mimeType)
{
    if (dptr->m_mimeType != mimeType) {
        dptr.detach();
        dptr->m_mimeType = mimeType;
    }
}

void CloudFile::setMimeType(QString &&mimeType)
{
    if (dptr->m_mimeType != mimeType) {
        dptr.detach();
        dptr->m_mimeType = std::move(mimeType);
    }
}

void CloudFile::setSize(QtProtobuf::int64 size)
{
    if (dptr->m_size != size) {
        dptr.detach();
        dptr->m_size = size;
    }
}

void CloudFile::setCreatedTime(const QString &createdTime)
{
    if (dptr->m_createdTime != createdTime) {
        dptr.detach();
        dptr->m_createdTime = createdTime;
    }
}

void CloudFile::setCreatedTime(QString &&createdTime)
{
    if (dptr->m_createdTime != createdTime) {
        dptr.detach();
        dptr->m_createdTime = std::move(createdTime);
    }
}

void CloudFile::setSource(const QString &source)
{
    if (dptr->m_source != source) {
        dptr.detach();
        dptr->m_source = source;
    }
}

void CloudFile::setSource(QString &&source)
{
    if (dptr->m_source != source) {
        dptr.detach();
        dptr->m_source = std::move(source);
    }
}


class FileList_QtProtobufData : public QSharedData
{
public:
    FileList_QtProtobufData()
        : QSharedData()
    {
    }

    FileList_QtProtobufData(const FileList_QtProtobufData &other)
        : QSharedData(other),
          m_files(other.m_files)
    {
    }

    QList<CloudFile> m_files;
};

FileList::~FileList() = default;

static constexpr struct {
    QtProtobufPrivate::QProtobufPropertyOrdering::Data data;
    const std::array<uint, 5> qt_protobuf_FileList_uint_data;
    const char qt_protobuf_FileList_char_data[31];
} qt_protobuf_FileList_metadata {
    // data
    {
        0, /* = version */
        1, /* = num fields */
        2, /* = field number offset */
        3, /* = property index offset */
        4, /* = field flags offset */
        23, /* = message full name length */
    },
    // uint_data
    {
        // JSON name offsets:
        24, /* = files */
        30, /* = end-of-string-marker */
        // Field numbers:
        1, /* = files */
        // Property indices:
        0, /* = files */
        // Field flags:
        uint(QtProtobufPrivate::FieldFlag::Repeated | QtProtobufPrivate::FieldFlag::Message), /* = files */
    },
    // char_data
    /* metadata char_data: */
    "cloudseal.grpc.FileList\0" /* = full message name */
    /* field char_data: */
    "files\0"
};

const QtProtobufPrivate::QProtobufPropertyOrdering FileList::staticPropertyOrdering = {
    &qt_protobuf_FileList_metadata.data
};

void FileList::registerTypes()
{
    qRegisterMetaType<FileList>();
    qRegisterMetaType<QList<FileList>>();
}

FileList::FileList()
    : QProtobufMessage(&FileList::staticMetaObject, &FileList::staticPropertyOrdering),
      dptr(new FileList_QtProtobufData)
{
}

FileList::FileList(const FileList &other)
    = default;
FileList &FileList::operator =(const FileList &other)
{
    FileList temp(other);
    swap(temp);
    return *this;
}
FileList::FileList(FileList &&other) noexcept
    = default;
FileList::operator QVariant() const
{
    return QVariant::fromValue(*this);
}
bool comparesEqual(const FileList &lhs, const FileList &rhs) noexcept
{
    return operator ==(static_cast<const QProtobufMessage&>(lhs),
                       static_cast<const QProtobufMessage&>(rhs))
        && lhs.dptr->m_files == rhs.dptr->m_files;
}

const QList<CloudFile> &FileList::files() const &
{
    return dptr->m_files;
}

void FileList::setFiles(const QList<CloudFile> &files)
{
    if (dptr->m_files != files) {
        dptr.detach();
        dptr->m_files = files;
    }
}

void FileList::setFiles(QList<CloudFile> &&files)
{
    if (dptr->m_files != files) {
        dptr.detach();
        dptr->m_files = std::move(files);
    }
}


class AuthRequest_QtProtobufData : public QSharedData
{
public:
    AuthRequest_QtProtobufData()
        : QSharedData()
    {
    }

    AuthRequest_QtProtobufData(const AuthRequest_QtProtobufData &other)
        : QSharedData(other),
          m_username(other.m_username),
          m_password(other.m_password)
    {
    }

    QString m_username;
    QString m_password;
};

AuthRequest::~AuthRequest() = default;

static constexpr struct {
    QtProtobufPrivate::QProtobufPropertyOrdering::Data data;
    const std::array<uint, 9> qt_protobuf_AuthRequest_uint_data;
    const char qt_protobuf_AuthRequest_char_data[46];
} qt_protobuf_AuthRequest_metadata {
    // data
    {
        0, /* = version */
        2, /* = num fields */
        3, /* = field number offset */
        5, /* = property index offset */
        7, /* = field flags offset */
        26, /* = message full name length */
    },
    // uint_data
    {
        // JSON name offsets:
        27, /* = username */
        36, /* = password */
        45, /* = end-of-string-marker */
        // Field numbers:
        1, /* = username */
        2, /* = password */
        // Property indices:
        0, /* = username */
        1, /* = password */
        // Field flags:
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = username */
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = password */
    },
    // char_data
    /* metadata char_data: */
    "cloudseal.grpc.AuthRequest\0" /* = full message name */
    /* field char_data: */
    "username\0password\0"
};

const QtProtobufPrivate::QProtobufPropertyOrdering AuthRequest::staticPropertyOrdering = {
    &qt_protobuf_AuthRequest_metadata.data
};

void AuthRequest::registerTypes()
{
    qRegisterMetaType<AuthRequest>();
    qRegisterMetaType<QList<AuthRequest>>();
}

AuthRequest::AuthRequest()
    : QProtobufMessage(&AuthRequest::staticMetaObject, &AuthRequest::staticPropertyOrdering),
      dptr(new AuthRequest_QtProtobufData)
{
}

AuthRequest::AuthRequest(const AuthRequest &other)
    = default;
AuthRequest &AuthRequest::operator =(const AuthRequest &other)
{
    AuthRequest temp(other);
    swap(temp);
    return *this;
}
AuthRequest::AuthRequest(AuthRequest &&other) noexcept
    = default;
AuthRequest::operator QVariant() const
{
    return QVariant::fromValue(*this);
}
bool comparesEqual(const AuthRequest &lhs, const AuthRequest &rhs) noexcept
{
    return operator ==(static_cast<const QProtobufMessage&>(lhs),
                       static_cast<const QProtobufMessage&>(rhs))
        && lhs.dptr->m_username == rhs.dptr->m_username
        && lhs.dptr->m_password == rhs.dptr->m_password;
}

const QString &AuthRequest::username() const &
{
    return dptr->m_username;
}

const QString &AuthRequest::password() const &
{
    return dptr->m_password;
}

void AuthRequest::setUsername(const QString &username)
{
    if (dptr->m_username != username) {
        dptr.detach();
        dptr->m_username = username;
    }
}

void AuthRequest::setUsername(QString &&username)
{
    if (dptr->m_username != username) {
        dptr.detach();
        dptr->m_username = std::move(username);
    }
}

void AuthRequest::setPassword(const QString &password)
{
    if (dptr->m_password != password) {
        dptr.detach();
        dptr->m_password = password;
    }
}

void AuthRequest::setPassword(QString &&password)
{
    if (dptr->m_password != password) {
        dptr.detach();
        dptr->m_password = std::move(password);
    }
}


class AuthResponse_QtProtobufData : public QSharedData
{
public:
    AuthResponse_QtProtobufData()
        : QSharedData(),
          m_success(false)
    {
    }

    AuthResponse_QtProtobufData(const AuthResponse_QtProtobufData &other)
        : QSharedData(other),
          m_success(other.m_success),
          m_message(other.m_message),
          m_token(other.m_token)
    {
    }

    bool m_success;
    QString m_message;
    QString m_token;
};

AuthResponse::~AuthResponse() = default;

static constexpr struct {
    QtProtobufPrivate::QProtobufPropertyOrdering::Data data;
    const std::array<uint, 13> qt_protobuf_AuthResponse_uint_data;
    const char qt_protobuf_AuthResponse_char_data[51];
} qt_protobuf_AuthResponse_metadata {
    // data
    {
        0, /* = version */
        3, /* = num fields */
        4, /* = field number offset */
        7, /* = property index offset */
        10, /* = field flags offset */
        27, /* = message full name length */
    },
    // uint_data
    {
        // JSON name offsets:
        28, /* = success */
        36, /* = message */
        44, /* = token */
        50, /* = end-of-string-marker */
        // Field numbers:
        1, /* = success */
        2, /* = message */
        3, /* = token */
        // Property indices:
        0, /* = success */
        1, /* = message */
        2, /* = token */
        // Field flags:
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = success */
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = message */
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = token */
    },
    // char_data
    /* metadata char_data: */
    "cloudseal.grpc.AuthResponse\0" /* = full message name */
    /* field char_data: */
    "success\0message\0token\0"
};

const QtProtobufPrivate::QProtobufPropertyOrdering AuthResponse::staticPropertyOrdering = {
    &qt_protobuf_AuthResponse_metadata.data
};

void AuthResponse::registerTypes()
{
    qRegisterMetaType<AuthResponse>();
    qRegisterMetaType<QList<AuthResponse>>();
}

AuthResponse::AuthResponse()
    : QProtobufMessage(&AuthResponse::staticMetaObject, &AuthResponse::staticPropertyOrdering),
      dptr(new AuthResponse_QtProtobufData)
{
}

AuthResponse::AuthResponse(const AuthResponse &other)
    = default;
AuthResponse &AuthResponse::operator =(const AuthResponse &other)
{
    AuthResponse temp(other);
    swap(temp);
    return *this;
}
AuthResponse::AuthResponse(AuthResponse &&other) noexcept
    = default;
AuthResponse::operator QVariant() const
{
    return QVariant::fromValue(*this);
}
bool comparesEqual(const AuthResponse &lhs, const AuthResponse &rhs) noexcept
{
    return operator ==(static_cast<const QProtobufMessage&>(lhs),
                       static_cast<const QProtobufMessage&>(rhs))
        && lhs.dptr->m_success == rhs.dptr->m_success
        && lhs.dptr->m_message == rhs.dptr->m_message
        && lhs.dptr->m_token == rhs.dptr->m_token;
}

bool AuthResponse::success() const
{
    return dptr->m_success;
}

const QString &AuthResponse::message() const &
{
    return dptr->m_message;
}

const QString &AuthResponse::token() const &
{
    return dptr->m_token;
}

void AuthResponse::setSuccess(bool success)
{
    if (dptr->m_success != success) {
        dptr.detach();
        dptr->m_success = success;
    }
}

void AuthResponse::setMessage(const QString &message)
{
    if (dptr->m_message != message) {
        dptr.detach();
        dptr->m_message = message;
    }
}

void AuthResponse::setMessage(QString &&message)
{
    if (dptr->m_message != message) {
        dptr.detach();
        dptr->m_message = std::move(message);
    }
}

void AuthResponse::setToken(const QString &token)
{
    if (dptr->m_token != token) {
        dptr.detach();
        dptr->m_token = token;
    }
}

void AuthResponse::setToken(QString &&token)
{
    if (dptr->m_token != token) {
        dptr.detach();
        dptr->m_token = std::move(token);
    }
}


class AuthToken_QtProtobufData : public QSharedData
{
public:
    AuthToken_QtProtobufData()
        : QSharedData()
    {
    }

    AuthToken_QtProtobufData(const AuthToken_QtProtobufData &other)
        : QSharedData(other),
          m_token(other.m_token)
    {
    }

    QString m_token;
};

AuthToken::~AuthToken() = default;

static constexpr struct {
    QtProtobufPrivate::QProtobufPropertyOrdering::Data data;
    const std::array<uint, 5> qt_protobuf_AuthToken_uint_data;
    const char qt_protobuf_AuthToken_char_data[32];
} qt_protobuf_AuthToken_metadata {
    // data
    {
        0, /* = version */
        1, /* = num fields */
        2, /* = field number offset */
        3, /* = property index offset */
        4, /* = field flags offset */
        24, /* = message full name length */
    },
    // uint_data
    {
        // JSON name offsets:
        25, /* = token */
        31, /* = end-of-string-marker */
        // Field numbers:
        1, /* = token */
        // Property indices:
        0, /* = token */
        // Field flags:
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = token */
    },
    // char_data
    /* metadata char_data: */
    "cloudseal.grpc.AuthToken\0" /* = full message name */
    /* field char_data: */
    "token\0"
};

const QtProtobufPrivate::QProtobufPropertyOrdering AuthToken::staticPropertyOrdering = {
    &qt_protobuf_AuthToken_metadata.data
};

void AuthToken::registerTypes()
{
    qRegisterMetaType<AuthToken>();
    qRegisterMetaType<QList<AuthToken>>();
}

AuthToken::AuthToken()
    : QProtobufMessage(&AuthToken::staticMetaObject, &AuthToken::staticPropertyOrdering),
      dptr(new AuthToken_QtProtobufData)
{
}

AuthToken::AuthToken(const AuthToken &other)
    = default;
AuthToken &AuthToken::operator =(const AuthToken &other)
{
    AuthToken temp(other);
    swap(temp);
    return *this;
}
AuthToken::AuthToken(AuthToken &&other) noexcept
    = default;
AuthToken::operator QVariant() const
{
    return QVariant::fromValue(*this);
}
bool comparesEqual(const AuthToken &lhs, const AuthToken &rhs) noexcept
{
    return operator ==(static_cast<const QProtobufMessage&>(lhs),
                       static_cast<const QProtobufMessage&>(rhs))
        && lhs.dptr->m_token == rhs.dptr->m_token;
}

const QString &AuthToken::token() const &
{
    return dptr->m_token;
}

void AuthToken::setToken(const QString &token)
{
    if (dptr->m_token != token) {
        dptr.detach();
        dptr->m_token = token;
    }
}

void AuthToken::setToken(QString &&token)
{
    if (dptr->m_token != token) {
        dptr.detach();
        dptr->m_token = std::move(token);
    }
}


class VaultRequest_QtProtobufData : public QSharedData
{
public:
    VaultRequest_QtProtobufData()
        : QSharedData()
    {
    }

    VaultRequest_QtProtobufData(const VaultRequest_QtProtobufData &other)
        : QSharedData(other),
          m_token(other.m_token),
          m_localPath(other.m_localPath)
    {
    }

    QString m_token;
    QString m_localPath;
};

VaultRequest::~VaultRequest() = default;

static constexpr struct {
    QtProtobufPrivate::QProtobufPropertyOrdering::Data data;
    const std::array<uint, 9> qt_protobuf_VaultRequest_uint_data;
    const char qt_protobuf_VaultRequest_char_data[45];
} qt_protobuf_VaultRequest_metadata {
    // data
    {
        0, /* = version */
        2, /* = num fields */
        3, /* = field number offset */
        5, /* = property index offset */
        7, /* = field flags offset */
        27, /* = message full name length */
    },
    // uint_data
    {
        // JSON name offsets:
        28, /* = token */
        34, /* = localPath */
        44, /* = end-of-string-marker */
        // Field numbers:
        1, /* = token */
        2, /* = localPath */
        // Property indices:
        0, /* = token */
        1, /* = localPath */
        // Field flags:
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = token */
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = localPath */
    },
    // char_data
    /* metadata char_data: */
    "cloudseal.grpc.VaultRequest\0" /* = full message name */
    /* field char_data: */
    "token\0localPath\0"
};

const QtProtobufPrivate::QProtobufPropertyOrdering VaultRequest::staticPropertyOrdering = {
    &qt_protobuf_VaultRequest_metadata.data
};

void VaultRequest::registerTypes()
{
    qRegisterMetaType<VaultRequest>();
    qRegisterMetaType<QList<VaultRequest>>();
}

VaultRequest::VaultRequest()
    : QProtobufMessage(&VaultRequest::staticMetaObject, &VaultRequest::staticPropertyOrdering),
      dptr(new VaultRequest_QtProtobufData)
{
}

VaultRequest::VaultRequest(const VaultRequest &other)
    = default;
VaultRequest &VaultRequest::operator =(const VaultRequest &other)
{
    VaultRequest temp(other);
    swap(temp);
    return *this;
}
VaultRequest::VaultRequest(VaultRequest &&other) noexcept
    = default;
VaultRequest::operator QVariant() const
{
    return QVariant::fromValue(*this);
}
bool comparesEqual(const VaultRequest &lhs, const VaultRequest &rhs) noexcept
{
    return operator ==(static_cast<const QProtobufMessage&>(lhs),
                       static_cast<const QProtobufMessage&>(rhs))
        && lhs.dptr->m_token == rhs.dptr->m_token
        && lhs.dptr->m_localPath == rhs.dptr->m_localPath;
}

const QString &VaultRequest::token() const &
{
    return dptr->m_token;
}

const QString &VaultRequest::localPath() const &
{
    return dptr->m_localPath;
}

void VaultRequest::setToken(const QString &token)
{
    if (dptr->m_token != token) {
        dptr.detach();
        dptr->m_token = token;
    }
}

void VaultRequest::setToken(QString &&token)
{
    if (dptr->m_token != token) {
        dptr.detach();
        dptr->m_token = std::move(token);
    }
}

void VaultRequest::setLocalPath(const QString &localPath)
{
    if (dptr->m_localPath != localPath) {
        dptr.detach();
        dptr->m_localPath = localPath;
    }
}

void VaultRequest::setLocalPath(QString &&localPath)
{
    if (dptr->m_localPath != localPath) {
        dptr.detach();
        dptr->m_localPath = std::move(localPath);
    }
}


class VaultQuery_QtProtobufData : public QSharedData
{
public:
    VaultQuery_QtProtobufData()
        : QSharedData()
    {
    }

    VaultQuery_QtProtobufData(const VaultQuery_QtProtobufData &other)
        : QSharedData(other),
          m_token(other.m_token)
    {
    }

    QString m_token;
};

VaultQuery::~VaultQuery() = default;

static constexpr struct {
    QtProtobufPrivate::QProtobufPropertyOrdering::Data data;
    const std::array<uint, 5> qt_protobuf_VaultQuery_uint_data;
    const char qt_protobuf_VaultQuery_char_data[33];
} qt_protobuf_VaultQuery_metadata {
    // data
    {
        0, /* = version */
        1, /* = num fields */
        2, /* = field number offset */
        3, /* = property index offset */
        4, /* = field flags offset */
        25, /* = message full name length */
    },
    // uint_data
    {
        // JSON name offsets:
        26, /* = token */
        32, /* = end-of-string-marker */
        // Field numbers:
        1, /* = token */
        // Property indices:
        0, /* = token */
        // Field flags:
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = token */
    },
    // char_data
    /* metadata char_data: */
    "cloudseal.grpc.VaultQuery\0" /* = full message name */
    /* field char_data: */
    "token\0"
};

const QtProtobufPrivate::QProtobufPropertyOrdering VaultQuery::staticPropertyOrdering = {
    &qt_protobuf_VaultQuery_metadata.data
};

void VaultQuery::registerTypes()
{
    qRegisterMetaType<VaultQuery>();
    qRegisterMetaType<QList<VaultQuery>>();
}

VaultQuery::VaultQuery()
    : QProtobufMessage(&VaultQuery::staticMetaObject, &VaultQuery::staticPropertyOrdering),
      dptr(new VaultQuery_QtProtobufData)
{
}

VaultQuery::VaultQuery(const VaultQuery &other)
    = default;
VaultQuery &VaultQuery::operator =(const VaultQuery &other)
{
    VaultQuery temp(other);
    swap(temp);
    return *this;
}
VaultQuery::VaultQuery(VaultQuery &&other) noexcept
    = default;
VaultQuery::operator QVariant() const
{
    return QVariant::fromValue(*this);
}
bool comparesEqual(const VaultQuery &lhs, const VaultQuery &rhs) noexcept
{
    return operator ==(static_cast<const QProtobufMessage&>(lhs),
                       static_cast<const QProtobufMessage&>(rhs))
        && lhs.dptr->m_token == rhs.dptr->m_token;
}

const QString &VaultQuery::token() const &
{
    return dptr->m_token;
}

void VaultQuery::setToken(const QString &token)
{
    if (dptr->m_token != token) {
        dptr.detach();
        dptr->m_token = token;
    }
}

void VaultQuery::setToken(QString &&token)
{
    if (dptr->m_token != token) {
        dptr.detach();
        dptr->m_token = std::move(token);
    }
}


class VaultResponse_QtProtobufData : public QSharedData
{
public:
    VaultResponse_QtProtobufData()
        : QSharedData()
    {
    }

    VaultResponse_QtProtobufData(const VaultResponse_QtProtobufData &other)
        : QSharedData(other),
          m_localPath(other.m_localPath)
    {
    }

    QString m_localPath;
};

VaultResponse::~VaultResponse() = default;

static constexpr struct {
    QtProtobufPrivate::QProtobufPropertyOrdering::Data data;
    const std::array<uint, 5> qt_protobuf_VaultResponse_uint_data;
    const char qt_protobuf_VaultResponse_char_data[40];
} qt_protobuf_VaultResponse_metadata {
    // data
    {
        0, /* = version */
        1, /* = num fields */
        2, /* = field number offset */
        3, /* = property index offset */
        4, /* = field flags offset */
        28, /* = message full name length */
    },
    // uint_data
    {
        // JSON name offsets:
        29, /* = localPath */
        39, /* = end-of-string-marker */
        // Field numbers:
        1, /* = localPath */
        // Property indices:
        0, /* = localPath */
        // Field flags:
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = localPath */
    },
    // char_data
    /* metadata char_data: */
    "cloudseal.grpc.VaultResponse\0" /* = full message name */
    /* field char_data: */
    "localPath\0"
};

const QtProtobufPrivate::QProtobufPropertyOrdering VaultResponse::staticPropertyOrdering = {
    &qt_protobuf_VaultResponse_metadata.data
};

void VaultResponse::registerTypes()
{
    qRegisterMetaType<VaultResponse>();
    qRegisterMetaType<QList<VaultResponse>>();
}

VaultResponse::VaultResponse()
    : QProtobufMessage(&VaultResponse::staticMetaObject, &VaultResponse::staticPropertyOrdering),
      dptr(new VaultResponse_QtProtobufData)
{
}

VaultResponse::VaultResponse(const VaultResponse &other)
    = default;
VaultResponse &VaultResponse::operator =(const VaultResponse &other)
{
    VaultResponse temp(other);
    swap(temp);
    return *this;
}
VaultResponse::VaultResponse(VaultResponse &&other) noexcept
    = default;
VaultResponse::operator QVariant() const
{
    return QVariant::fromValue(*this);
}
bool comparesEqual(const VaultResponse &lhs, const VaultResponse &rhs) noexcept
{
    return operator ==(static_cast<const QProtobufMessage&>(lhs),
                       static_cast<const QProtobufMessage&>(rhs))
        && lhs.dptr->m_localPath == rhs.dptr->m_localPath;
}

const QString &VaultResponse::localPath() const &
{
    return dptr->m_localPath;
}

void VaultResponse::setLocalPath(const QString &localPath)
{
    if (dptr->m_localPath != localPath) {
        dptr.detach();
        dptr->m_localPath = localPath;
    }
}

void VaultResponse::setLocalPath(QString &&localPath)
{
    if (dptr->m_localPath != localPath) {
        dptr.detach();
        dptr->m_localPath = std::move(localPath);
    }
}


class FileTransferPath_QtProtobufData : public QSharedData
{
public:
    FileTransferPath_QtProtobufData()
        : QSharedData()
    {
    }

    FileTransferPath_QtProtobufData(const FileTransferPath_QtProtobufData &other)
        : QSharedData(other),
          m_token(other.m_token),
          m_remoteName(other.m_remoteName),
          m_localPath(other.m_localPath)
    {
    }

    QString m_token;
    QString m_remoteName;
    QString m_localPath;
};

FileTransferPath::~FileTransferPath() = default;

static constexpr struct {
    QtProtobufPrivate::QProtobufPropertyOrdering::Data data;
    const std::array<uint, 13> qt_protobuf_FileTransferPath_uint_data;
    const char qt_protobuf_FileTransferPath_char_data[60];
} qt_protobuf_FileTransferPath_metadata {
    // data
    {
        0, /* = version */
        3, /* = num fields */
        4, /* = field number offset */
        7, /* = property index offset */
        10, /* = field flags offset */
        31, /* = message full name length */
    },
    // uint_data
    {
        // JSON name offsets:
        32, /* = token */
        38, /* = remoteName */
        49, /* = localPath */
        59, /* = end-of-string-marker */
        // Field numbers:
        1, /* = token */
        2, /* = remoteName */
        3, /* = localPath */
        // Property indices:
        0, /* = token */
        1, /* = remoteName */
        2, /* = localPath */
        // Field flags:
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = token */
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = remoteName */
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = localPath */
    },
    // char_data
    /* metadata char_data: */
    "cloudseal.grpc.FileTransferPath\0" /* = full message name */
    /* field char_data: */
    "token\0remoteName\0localPath\0"
};

const QtProtobufPrivate::QProtobufPropertyOrdering FileTransferPath::staticPropertyOrdering = {
    &qt_protobuf_FileTransferPath_metadata.data
};

void FileTransferPath::registerTypes()
{
    qRegisterMetaType<FileTransferPath>();
    qRegisterMetaType<QList<FileTransferPath>>();
}

FileTransferPath::FileTransferPath()
    : QProtobufMessage(&FileTransferPath::staticMetaObject, &FileTransferPath::staticPropertyOrdering),
      dptr(new FileTransferPath_QtProtobufData)
{
}

FileTransferPath::FileTransferPath(const FileTransferPath &other)
    = default;
FileTransferPath &FileTransferPath::operator =(const FileTransferPath &other)
{
    FileTransferPath temp(other);
    swap(temp);
    return *this;
}
FileTransferPath::FileTransferPath(FileTransferPath &&other) noexcept
    = default;
FileTransferPath::operator QVariant() const
{
    return QVariant::fromValue(*this);
}
bool comparesEqual(const FileTransferPath &lhs, const FileTransferPath &rhs) noexcept
{
    return operator ==(static_cast<const QProtobufMessage&>(lhs),
                       static_cast<const QProtobufMessage&>(rhs))
        && lhs.dptr->m_token == rhs.dptr->m_token
        && lhs.dptr->m_remoteName == rhs.dptr->m_remoteName
        && lhs.dptr->m_localPath == rhs.dptr->m_localPath;
}

const QString &FileTransferPath::token() const &
{
    return dptr->m_token;
}

const QString &FileTransferPath::remoteName() const &
{
    return dptr->m_remoteName;
}

const QString &FileTransferPath::localPath() const &
{
    return dptr->m_localPath;
}

void FileTransferPath::setToken(const QString &token)
{
    if (dptr->m_token != token) {
        dptr.detach();
        dptr->m_token = token;
    }
}

void FileTransferPath::setToken(QString &&token)
{
    if (dptr->m_token != token) {
        dptr.detach();
        dptr->m_token = std::move(token);
    }
}

void FileTransferPath::setRemoteName(const QString &remoteName)
{
    if (dptr->m_remoteName != remoteName) {
        dptr.detach();
        dptr->m_remoteName = remoteName;
    }
}

void FileTransferPath::setRemoteName(QString &&remoteName)
{
    if (dptr->m_remoteName != remoteName) {
        dptr.detach();
        dptr->m_remoteName = std::move(remoteName);
    }
}

void FileTransferPath::setLocalPath(const QString &localPath)
{
    if (dptr->m_localPath != localPath) {
        dptr.detach();
        dptr->m_localPath = localPath;
    }
}

void FileTransferPath::setLocalPath(QString &&localPath)
{
    if (dptr->m_localPath != localPath) {
        dptr.detach();
        dptr->m_localPath = std::move(localPath);
    }
}


class GlobalStats_QtProtobufData : public QSharedData
{
public:
    GlobalStats_QtProtobufData()
        : QSharedData(),
          m_total(0),
          m_free(0)
    {
    }

    GlobalStats_QtProtobufData(const GlobalStats_QtProtobufData &other)
        : QSharedData(other),
          m_total(other.m_total),
          m_free(other.m_free)
    {
    }

    QtProtobuf::int64 m_total;
    QtProtobuf::int64 m_free;
};

GlobalStats::~GlobalStats() = default;

static constexpr struct {
    QtProtobufPrivate::QProtobufPropertyOrdering::Data data;
    const std::array<uint, 9> qt_protobuf_GlobalStats_uint_data;
    const char qt_protobuf_GlobalStats_char_data[39];
} qt_protobuf_GlobalStats_metadata {
    // data
    {
        0, /* = version */
        2, /* = num fields */
        3, /* = field number offset */
        5, /* = property index offset */
        7, /* = field flags offset */
        26, /* = message full name length */
    },
    // uint_data
    {
        // JSON name offsets:
        27, /* = total */
        33, /* = free */
        38, /* = end-of-string-marker */
        // Field numbers:
        1, /* = total */
        2, /* = free */
        // Property indices:
        0, /* = total */
        1, /* = free */
        // Field flags:
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = total */
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = free */
    },
    // char_data
    /* metadata char_data: */
    "cloudseal.grpc.GlobalStats\0" /* = full message name */
    /* field char_data: */
    "total\0free\0"
};

const QtProtobufPrivate::QProtobufPropertyOrdering GlobalStats::staticPropertyOrdering = {
    &qt_protobuf_GlobalStats_metadata.data
};

void GlobalStats::registerTypes()
{
    qRegisterMetaType<GlobalStats>();
    qRegisterMetaType<QList<GlobalStats>>();
}

GlobalStats::GlobalStats()
    : QProtobufMessage(&GlobalStats::staticMetaObject, &GlobalStats::staticPropertyOrdering),
      dptr(new GlobalStats_QtProtobufData)
{
}

GlobalStats::GlobalStats(const GlobalStats &other)
    = default;
GlobalStats &GlobalStats::operator =(const GlobalStats &other)
{
    GlobalStats temp(other);
    swap(temp);
    return *this;
}
GlobalStats::GlobalStats(GlobalStats &&other) noexcept
    = default;
GlobalStats::operator QVariant() const
{
    return QVariant::fromValue(*this);
}
bool comparesEqual(const GlobalStats &lhs, const GlobalStats &rhs) noexcept
{
    return operator ==(static_cast<const QProtobufMessage&>(lhs),
                       static_cast<const QProtobufMessage&>(rhs))
        && lhs.dptr->m_total == rhs.dptr->m_total
        && lhs.dptr->m_free == rhs.dptr->m_free;
}

QtProtobuf::int64 GlobalStats::total() const
{
    return dptr->m_total;
}

QtProtobuf::int64 GlobalStats::free() const
{
    return dptr->m_free;
}

void GlobalStats::setTotal(QtProtobuf::int64 total)
{
    if (dptr->m_total != total) {
        dptr.detach();
        dptr->m_total = total;
    }
}

void GlobalStats::setFree(QtProtobuf::int64 free)
{
    if (dptr->m_free != free) {
        dptr.detach();
        dptr->m_free = free;
    }
}


class Status_QtProtobufData : public QSharedData
{
public:
    Status_QtProtobufData()
        : QSharedData(),
          m_success(false)
    {
    }

    Status_QtProtobufData(const Status_QtProtobufData &other)
        : QSharedData(other),
          m_success(other.m_success),
          m_message(other.m_message)
    {
    }

    bool m_success;
    QString m_message;
};

Status::~Status() = default;

static constexpr struct {
    QtProtobufPrivate::QProtobufPropertyOrdering::Data data;
    const std::array<uint, 9> qt_protobuf_Status_uint_data;
    const char qt_protobuf_Status_char_data[39];
} qt_protobuf_Status_metadata {
    // data
    {
        0, /* = version */
        2, /* = num fields */
        3, /* = field number offset */
        5, /* = property index offset */
        7, /* = field flags offset */
        21, /* = message full name length */
    },
    // uint_data
    {
        // JSON name offsets:
        22, /* = success */
        30, /* = message */
        38, /* = end-of-string-marker */
        // Field numbers:
        1, /* = success */
        2, /* = message */
        // Property indices:
        0, /* = success */
        1, /* = message */
        // Field flags:
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = success */
        uint(QtProtobufPrivate::FieldFlag::NoFlags), /* = message */
    },
    // char_data
    /* metadata char_data: */
    "cloudseal.grpc.Status\0" /* = full message name */
    /* field char_data: */
    "success\0message\0"
};

const QtProtobufPrivate::QProtobufPropertyOrdering Status::staticPropertyOrdering = {
    &qt_protobuf_Status_metadata.data
};

void Status::registerTypes()
{
    qRegisterMetaType<Status>();
    qRegisterMetaType<QList<Status>>();
}

Status::Status()
    : QProtobufMessage(&Status::staticMetaObject, &Status::staticPropertyOrdering),
      dptr(new Status_QtProtobufData)
{
}

Status::Status(const Status &other)
    = default;
Status &Status::operator =(const Status &other)
{
    Status temp(other);
    swap(temp);
    return *this;
}
Status::Status(Status &&other) noexcept
    = default;
Status::operator QVariant() const
{
    return QVariant::fromValue(*this);
}
bool comparesEqual(const Status &lhs, const Status &rhs) noexcept
{
    return operator ==(static_cast<const QProtobufMessage&>(lhs),
                       static_cast<const QProtobufMessage&>(rhs))
        && lhs.dptr->m_success == rhs.dptr->m_success
        && lhs.dptr->m_message == rhs.dptr->m_message;
}

bool Status::success() const
{
    return dptr->m_success;
}

const QString &Status::message() const &
{
    return dptr->m_message;
}

void Status::setSuccess(bool success)
{
    if (dptr->m_success != success) {
        dptr.detach();
        dptr->m_success = success;
    }
}

void Status::setMessage(const QString &message)
{
    if (dptr->m_message != message) {
        dptr.detach();
        dptr->m_message = message;
    }
}

void Status::setMessage(QString &&message)
{
    if (dptr->m_message != message) {
        dptr.detach();
        dptr->m_message = std::move(message);
    }
}

} // namespace cloudseal::grpc

#include "moc_cloudseal.qpb.cpp"
