/* This file is autogenerated. DO NOT CHANGE. All changes will be lost */

#ifndef CLOUDSEAL_CLIENT_GRPC_QPB_H
#define CLOUDSEAL_CLIENT_GRPC_QPB_H

#include "cloudseal/grpc/cloudseal.qpb.h"

#include <QtGrpc/qgrpccallreply.h>
#include <QtGrpc/qgrpcclientbase.h>
#include <QtGrpc/qgrpcstream.h>

#include <memory>

namespace cloudseal::grpc {
namespace CloudSeal {

class Client : public QGrpcClientBase
{
    Q_OBJECT

public:
    explicit Client(QObject *parent = nullptr);
    ~Client() override;

    [[nodiscard]]
    std::unique_ptr<QGrpcCallReply> Register(const cloudseal::grpc::AuthRequest &arg);
    [[nodiscard]]
    std::unique_ptr<QGrpcCallReply> Register(const cloudseal::grpc::AuthRequest &arg, const QGrpcCallOptions &options);

    [[nodiscard]]
    std::unique_ptr<QGrpcCallReply> Login(const cloudseal::grpc::AuthRequest &arg);
    [[nodiscard]]
    std::unique_ptr<QGrpcCallReply> Login(const cloudseal::grpc::AuthRequest &arg, const QGrpcCallOptions &options);

    [[nodiscard]]
    std::unique_ptr<QGrpcCallReply> UploadVault(const cloudseal::grpc::VaultRequest &arg);
    [[nodiscard]]
    std::unique_ptr<QGrpcCallReply> UploadVault(const cloudseal::grpc::VaultRequest &arg, const QGrpcCallOptions &options);

    [[nodiscard]]
    std::unique_ptr<QGrpcCallReply> DownloadVault(const cloudseal::grpc::VaultQuery &arg);
    [[nodiscard]]
    std::unique_ptr<QGrpcCallReply> DownloadVault(const cloudseal::grpc::VaultQuery &arg, const QGrpcCallOptions &options);

    [[nodiscard]]
    std::unique_ptr<QGrpcCallReply> UploadFile(const cloudseal::grpc::FileTransferPath &arg);
    [[nodiscard]]
    std::unique_ptr<QGrpcCallReply> UploadFile(const cloudseal::grpc::FileTransferPath &arg, const QGrpcCallOptions &options);

    [[nodiscard]]
    std::unique_ptr<QGrpcCallReply> DownloadFile(const cloudseal::grpc::FileTransferPath &arg);
    [[nodiscard]]
    std::unique_ptr<QGrpcCallReply> DownloadFile(const cloudseal::grpc::FileTransferPath &arg, const QGrpcCallOptions &options);

    [[nodiscard]]
    std::unique_ptr<QGrpcCallReply> ListFiles(const cloudseal::grpc::AuthToken &arg);
    [[nodiscard]]
    std::unique_ptr<QGrpcCallReply> ListFiles(const cloudseal::grpc::AuthToken &arg, const QGrpcCallOptions &options);

    [[nodiscard]]
    std::unique_ptr<QGrpcCallReply> GetStats(const cloudseal::grpc::AuthToken &arg);
    [[nodiscard]]
    std::unique_ptr<QGrpcCallReply> GetStats(const cloudseal::grpc::AuthToken &arg, const QGrpcCallOptions &options);


};
} // namespace CloudSeal
} // namespace cloudseal::grpc

#endif // CLOUDSEAL_CLIENT_GRPC_QPB_H
