/* This file is autogenerated. DO NOT CHANGE. All changes will be lost */

#include "cloudseal/grpc/cloudseal_client.grpc.qpb.h"

namespace cloudseal::grpc {
namespace CloudSeal {
using namespace Qt::StringLiterals;

Client::Client(QObject *parent)
    : QGrpcClientBase("cloudseal.grpc.CloudSeal"_L1, parent)
{
}

Client::~Client() = default;

std::unique_ptr<QGrpcCallReply> Client::Register(const cloudseal::grpc::AuthRequest &arg)
{
    return Register(arg, {});
}


std::unique_ptr<QGrpcCallReply> Client::Register(const cloudseal::grpc::AuthRequest &arg, const QGrpcCallOptions &options)
{
    auto reply = call("Register"_L1, arg, options);
    if (auto *replyPtr = reply.get(); replyPtr != nullptr) {
        setOperationResponseMetaType(replyPtr, QMetaType::fromType<cloudseal::grpc::AuthResponse>());
    }
    return reply;
}


std::unique_ptr<QGrpcCallReply> Client::Login(const cloudseal::grpc::AuthRequest &arg)
{
    return Login(arg, {});
}


std::unique_ptr<QGrpcCallReply> Client::Login(const cloudseal::grpc::AuthRequest &arg, const QGrpcCallOptions &options)
{
    auto reply = call("Login"_L1, arg, options);
    if (auto *replyPtr = reply.get(); replyPtr != nullptr) {
        setOperationResponseMetaType(replyPtr, QMetaType::fromType<cloudseal::grpc::AuthResponse>());
    }
    return reply;
}


std::unique_ptr<QGrpcCallReply> Client::UploadVault(const cloudseal::grpc::VaultRequest &arg)
{
    return UploadVault(arg, {});
}


std::unique_ptr<QGrpcCallReply> Client::UploadVault(const cloudseal::grpc::VaultRequest &arg, const QGrpcCallOptions &options)
{
    auto reply = call("UploadVault"_L1, arg, options);
    if (auto *replyPtr = reply.get(); replyPtr != nullptr) {
        setOperationResponseMetaType(replyPtr, QMetaType::fromType<cloudseal::grpc::Status>());
    }
    return reply;
}


std::unique_ptr<QGrpcCallReply> Client::DownloadVault(const cloudseal::grpc::VaultQuery &arg)
{
    return DownloadVault(arg, {});
}


std::unique_ptr<QGrpcCallReply> Client::DownloadVault(const cloudseal::grpc::VaultQuery &arg, const QGrpcCallOptions &options)
{
    auto reply = call("DownloadVault"_L1, arg, options);
    if (auto *replyPtr = reply.get(); replyPtr != nullptr) {
        setOperationResponseMetaType(replyPtr, QMetaType::fromType<cloudseal::grpc::VaultResponse>());
    }
    return reply;
}


std::unique_ptr<QGrpcCallReply> Client::UploadFile(const cloudseal::grpc::FileTransferPath &arg)
{
    return UploadFile(arg, {});
}


std::unique_ptr<QGrpcCallReply> Client::UploadFile(const cloudseal::grpc::FileTransferPath &arg, const QGrpcCallOptions &options)
{
    auto reply = call("UploadFile"_L1, arg, options);
    if (auto *replyPtr = reply.get(); replyPtr != nullptr) {
        setOperationResponseMetaType(replyPtr, QMetaType::fromType<cloudseal::grpc::Status>());
    }
    return reply;
}


std::unique_ptr<QGrpcCallReply> Client::DownloadFile(const cloudseal::grpc::FileTransferPath &arg)
{
    return DownloadFile(arg, {});
}


std::unique_ptr<QGrpcCallReply> Client::DownloadFile(const cloudseal::grpc::FileTransferPath &arg, const QGrpcCallOptions &options)
{
    auto reply = call("DownloadFile"_L1, arg, options);
    if (auto *replyPtr = reply.get(); replyPtr != nullptr) {
        setOperationResponseMetaType(replyPtr, QMetaType::fromType<cloudseal::grpc::Status>());
    }
    return reply;
}


std::unique_ptr<QGrpcCallReply> Client::ListFiles(const cloudseal::grpc::AuthToken &arg)
{
    return ListFiles(arg, {});
}


std::unique_ptr<QGrpcCallReply> Client::ListFiles(const cloudseal::grpc::AuthToken &arg, const QGrpcCallOptions &options)
{
    auto reply = call("ListFiles"_L1, arg, options);
    if (auto *replyPtr = reply.get(); replyPtr != nullptr) {
        setOperationResponseMetaType(replyPtr, QMetaType::fromType<cloudseal::grpc::FileList>());
    }
    return reply;
}


std::unique_ptr<QGrpcCallReply> Client::GetStats(const cloudseal::grpc::AuthToken &arg)
{
    return GetStats(arg, {});
}


std::unique_ptr<QGrpcCallReply> Client::GetStats(const cloudseal::grpc::AuthToken &arg, const QGrpcCallOptions &options)
{
    auto reply = call("GetStats"_L1, arg, options);
    if (auto *replyPtr = reply.get(); replyPtr != nullptr) {
        setOperationResponseMetaType(replyPtr, QMetaType::fromType<cloudseal::grpc::GlobalStats>());
    }
    return reply;
}

} // namespace CloudSeal
} // namespace cloudseal::grpc

