/* This file is autogenerated. DO NOT CHANGE. All changes will be lost */

#ifndef CLOUDSEAL_QPB_H
#define CLOUDSEAL_QPB_H

#include <QtProtobuf/qprotobuflazymessagepointer.h>
#include <QtProtobuf/qprotobufmessage.h>
#include <QtProtobuf/qprotobufobject.h>
#include <QtProtobuf/qtprotobuftypes.h>

#include <QtCore/qbytearray.h>
#include <QtCore/qlist.h>
#include <QtCore/qmetatype.h>
#include <QtCore/qshareddata.h>
#include <QtCore/qstring.h>

namespace cloudseal::grpc {
class CloudFile;
namespace CloudFile_QtProtobufNested {
enum class QtProtobufFieldEnum;
} // namespace CloudFile_QtProtobufNested

class FileList;
namespace FileList_QtProtobufNested {
enum class QtProtobufFieldEnum;
} // namespace FileList_QtProtobufNested

class AuthRequest;
namespace AuthRequest_QtProtobufNested {
enum class QtProtobufFieldEnum;
} // namespace AuthRequest_QtProtobufNested

class AuthResponse;
namespace AuthResponse_QtProtobufNested {
enum class QtProtobufFieldEnum;
} // namespace AuthResponse_QtProtobufNested

class AuthToken;
namespace AuthToken_QtProtobufNested {
enum class QtProtobufFieldEnum;
} // namespace AuthToken_QtProtobufNested

class VaultRequest;
namespace VaultRequest_QtProtobufNested {
enum class QtProtobufFieldEnum;
} // namespace VaultRequest_QtProtobufNested

class VaultQuery;
namespace VaultQuery_QtProtobufNested {
enum class QtProtobufFieldEnum;
} // namespace VaultQuery_QtProtobufNested

class VaultResponse;
namespace VaultResponse_QtProtobufNested {
enum class QtProtobufFieldEnum;
} // namespace VaultResponse_QtProtobufNested

class FileTransferPath;
namespace FileTransferPath_QtProtobufNested {
enum class QtProtobufFieldEnum;
} // namespace FileTransferPath_QtProtobufNested

class GlobalStats;
namespace GlobalStats_QtProtobufNested {
enum class QtProtobufFieldEnum;
} // namespace GlobalStats_QtProtobufNested

class Status;
namespace Status_QtProtobufNested {
enum class QtProtobufFieldEnum;
} // namespace Status_QtProtobufNested

#ifdef QT_USE_PROTOBUF_LIST_ALIASES
using CloudFileRepeated = QList<CloudFile>;
using FileListRepeated = QList<FileList>;
using AuthRequestRepeated = QList<AuthRequest>;
using AuthResponseRepeated = QList<AuthResponse>;
using AuthTokenRepeated = QList<AuthToken>;
using VaultRequestRepeated = QList<VaultRequest>;
using VaultQueryRepeated = QList<VaultQuery>;
using VaultResponseRepeated = QList<VaultResponse>;
using FileTransferPathRepeated = QList<FileTransferPath>;
using GlobalStatsRepeated = QList<GlobalStats>;
using StatusRepeated = QList<Status>;
#endif // QT_USE_PROTOBUF_LIST_ALIASES

class CloudFile_QtProtobufData;
class CloudFile : public QProtobufMessage
{
    Q_PROTOBUF_OBJECT
    Q_PROPERTY(QString id_proto READ id_proto WRITE setId_proto SCRIPTABLE true)
    Q_PROPERTY(QString name READ name WRITE setName SCRIPTABLE true)
    Q_PROPERTY(QString mimeType READ mimeType WRITE setMimeType SCRIPTABLE true)
    Q_PROPERTY(QtProtobuf::int64 size READ size WRITE setSize SCRIPTABLE false)
    Q_PROPERTY(QString createdTime READ createdTime WRITE setCreatedTime SCRIPTABLE true)
    Q_PROPERTY(QString source READ source WRITE setSource SCRIPTABLE true)

public:
    using QtProtobufFieldEnum = CloudFile_QtProtobufNested::QtProtobufFieldEnum;
    CloudFile();
    ~CloudFile();
    CloudFile(const CloudFile &other);
    CloudFile &operator =(const CloudFile &other);
    CloudFile(CloudFile &&other) noexcept;
    CloudFile &operator =(CloudFile &&other) noexcept
    {
        swap(other);
        return *this;
    }
    void swap(CloudFile &other) noexcept
    {
        QProtobufMessage::swap(other);
        dptr.swap(other.dptr);
    }
    Q_IMPLICIT operator QVariant() const;

    const QString &id_proto() const &;

    const QString &name() const &;

    const QString &mimeType() const &;

    QtProtobuf::int64 size() const;

    const QString &createdTime() const &;

    const QString &source() const &;
    void setId_proto(const QString &id_proto);
    void setId_proto(QString &&id_proto);
    void setName(const QString &name);
    void setName(QString &&name);
    void setMimeType(const QString &mimeType);
    void setMimeType(QString &&mimeType);
    void setSize(QtProtobuf::int64 size);
    void setCreatedTime(const QString &createdTime);
    void setCreatedTime(QString &&createdTime);
    void setSource(const QString &source);
    void setSource(QString &&source);
    static void registerTypes();

private:
    friend bool comparesEqual(const CloudFile &lhs, const CloudFile &rhs) noexcept;
    friend bool operator==(const CloudFile &lhs, const CloudFile &rhs) noexcept
    {
        return comparesEqual(lhs, rhs);
    }
    friend bool operator!=(const CloudFile &lhs, const CloudFile &rhs) noexcept
    {
        return !comparesEqual(lhs, rhs);
    }
    QExplicitlySharedDataPointer<CloudFile_QtProtobufData> dptr;
};
namespace CloudFile_QtProtobufNested {
Q_NAMESPACE

enum class QtProtobufFieldEnum {
    Id_protoProtoFieldNumber = 1,
    NameProtoFieldNumber = 2,
    MimeTypeProtoFieldNumber = 3,
    SizeProtoFieldNumber = 4,
    CreatedTimeProtoFieldNumber = 5,
    SourceProtoFieldNumber = 6,
};
Q_ENUM_NS(QtProtobufFieldEnum)

} // namespace CloudFile_QtProtobufNested

class FileList_QtProtobufData;
class FileList : public QProtobufMessage
{
    Q_PROTOBUF_OBJECT
    Q_PROPERTY(QList<cloudseal::grpc::CloudFile> filesData READ files WRITE setFiles SCRIPTABLE true)

public:
    using QtProtobufFieldEnum = FileList_QtProtobufNested::QtProtobufFieldEnum;
    FileList();
    ~FileList();
    FileList(const FileList &other);
    FileList &operator =(const FileList &other);
    FileList(FileList &&other) noexcept;
    FileList &operator =(FileList &&other) noexcept
    {
        swap(other);
        return *this;
    }
    void swap(FileList &other) noexcept
    {
        QProtobufMessage::swap(other);
        dptr.swap(other.dptr);
    }
    Q_IMPLICIT operator QVariant() const;

    const QList<CloudFile> &files() const &;
    void setFiles(const QList<CloudFile> &files);
    void setFiles(QList<CloudFile> &&files);
    static void registerTypes();

private:
    friend bool comparesEqual(const FileList &lhs, const FileList &rhs) noexcept;
    friend bool operator==(const FileList &lhs, const FileList &rhs) noexcept
    {
        return comparesEqual(lhs, rhs);
    }
    friend bool operator!=(const FileList &lhs, const FileList &rhs) noexcept
    {
        return !comparesEqual(lhs, rhs);
    }
    QExplicitlySharedDataPointer<FileList_QtProtobufData> dptr;
};
namespace FileList_QtProtobufNested {
Q_NAMESPACE

enum class QtProtobufFieldEnum {
    FilesProtoFieldNumber = 1,
};
Q_ENUM_NS(QtProtobufFieldEnum)

} // namespace FileList_QtProtobufNested

class AuthRequest_QtProtobufData;
class AuthRequest : public QProtobufMessage
{
    Q_PROTOBUF_OBJECT
    Q_PROPERTY(QString username READ username WRITE setUsername SCRIPTABLE true)
    Q_PROPERTY(QString password READ password WRITE setPassword SCRIPTABLE true)

public:
    using QtProtobufFieldEnum = AuthRequest_QtProtobufNested::QtProtobufFieldEnum;
    AuthRequest();
    ~AuthRequest();
    AuthRequest(const AuthRequest &other);
    AuthRequest &operator =(const AuthRequest &other);
    AuthRequest(AuthRequest &&other) noexcept;
    AuthRequest &operator =(AuthRequest &&other) noexcept
    {
        swap(other);
        return *this;
    }
    void swap(AuthRequest &other) noexcept
    {
        QProtobufMessage::swap(other);
        dptr.swap(other.dptr);
    }
    Q_IMPLICIT operator QVariant() const;

    const QString &username() const &;

    const QString &password() const &;
    void setUsername(const QString &username);
    void setUsername(QString &&username);
    void setPassword(const QString &password);
    void setPassword(QString &&password);
    static void registerTypes();

private:
    friend bool comparesEqual(const AuthRequest &lhs, const AuthRequest &rhs) noexcept;
    friend bool operator==(const AuthRequest &lhs, const AuthRequest &rhs) noexcept
    {
        return comparesEqual(lhs, rhs);
    }
    friend bool operator!=(const AuthRequest &lhs, const AuthRequest &rhs) noexcept
    {
        return !comparesEqual(lhs, rhs);
    }
    QExplicitlySharedDataPointer<AuthRequest_QtProtobufData> dptr;
};
namespace AuthRequest_QtProtobufNested {
Q_NAMESPACE

enum class QtProtobufFieldEnum {
    UsernameProtoFieldNumber = 1,
    PasswordProtoFieldNumber = 2,
};
Q_ENUM_NS(QtProtobufFieldEnum)

} // namespace AuthRequest_QtProtobufNested

class AuthResponse_QtProtobufData;
class AuthResponse : public QProtobufMessage
{
    Q_PROTOBUF_OBJECT
    Q_PROPERTY(bool success READ success WRITE setSuccess SCRIPTABLE true)
    Q_PROPERTY(QString message READ message WRITE setMessage SCRIPTABLE true)
    Q_PROPERTY(QString token READ token WRITE setToken SCRIPTABLE true)

public:
    using QtProtobufFieldEnum = AuthResponse_QtProtobufNested::QtProtobufFieldEnum;
    AuthResponse();
    ~AuthResponse();
    AuthResponse(const AuthResponse &other);
    AuthResponse &operator =(const AuthResponse &other);
    AuthResponse(AuthResponse &&other) noexcept;
    AuthResponse &operator =(AuthResponse &&other) noexcept
    {
        swap(other);
        return *this;
    }
    void swap(AuthResponse &other) noexcept
    {
        QProtobufMessage::swap(other);
        dptr.swap(other.dptr);
    }
    Q_IMPLICIT operator QVariant() const;

    bool success() const;

    const QString &message() const &;

    const QString &token() const &;
    void setSuccess(bool success);
    void setMessage(const QString &message);
    void setMessage(QString &&message);
    void setToken(const QString &token);
    void setToken(QString &&token);
    static void registerTypes();

private:
    friend bool comparesEqual(const AuthResponse &lhs, const AuthResponse &rhs) noexcept;
    friend bool operator==(const AuthResponse &lhs, const AuthResponse &rhs) noexcept
    {
        return comparesEqual(lhs, rhs);
    }
    friend bool operator!=(const AuthResponse &lhs, const AuthResponse &rhs) noexcept
    {
        return !comparesEqual(lhs, rhs);
    }
    QExplicitlySharedDataPointer<AuthResponse_QtProtobufData> dptr;
};
namespace AuthResponse_QtProtobufNested {
Q_NAMESPACE

enum class QtProtobufFieldEnum {
    SuccessProtoFieldNumber = 1,
    MessageProtoFieldNumber = 2,
    TokenProtoFieldNumber = 3,
};
Q_ENUM_NS(QtProtobufFieldEnum)

} // namespace AuthResponse_QtProtobufNested

class AuthToken_QtProtobufData;
class AuthToken : public QProtobufMessage
{
    Q_PROTOBUF_OBJECT
    Q_PROPERTY(QString token READ token WRITE setToken SCRIPTABLE true)

public:
    using QtProtobufFieldEnum = AuthToken_QtProtobufNested::QtProtobufFieldEnum;
    AuthToken();
    ~AuthToken();
    AuthToken(const AuthToken &other);
    AuthToken &operator =(const AuthToken &other);
    AuthToken(AuthToken &&other) noexcept;
    AuthToken &operator =(AuthToken &&other) noexcept
    {
        swap(other);
        return *this;
    }
    void swap(AuthToken &other) noexcept
    {
        QProtobufMessage::swap(other);
        dptr.swap(other.dptr);
    }
    Q_IMPLICIT operator QVariant() const;

    const QString &token() const &;
    void setToken(const QString &token);
    void setToken(QString &&token);
    static void registerTypes();

private:
    friend bool comparesEqual(const AuthToken &lhs, const AuthToken &rhs) noexcept;
    friend bool operator==(const AuthToken &lhs, const AuthToken &rhs) noexcept
    {
        return comparesEqual(lhs, rhs);
    }
    friend bool operator!=(const AuthToken &lhs, const AuthToken &rhs) noexcept
    {
        return !comparesEqual(lhs, rhs);
    }
    QExplicitlySharedDataPointer<AuthToken_QtProtobufData> dptr;
};
namespace AuthToken_QtProtobufNested {
Q_NAMESPACE

enum class QtProtobufFieldEnum {
    TokenProtoFieldNumber = 1,
};
Q_ENUM_NS(QtProtobufFieldEnum)

} // namespace AuthToken_QtProtobufNested

class VaultRequest_QtProtobufData;
class VaultRequest : public QProtobufMessage
{
    Q_PROTOBUF_OBJECT
    Q_PROPERTY(QString token READ token WRITE setToken SCRIPTABLE true)
    Q_PROPERTY(QString localPath READ localPath WRITE setLocalPath SCRIPTABLE true)

public:
    using QtProtobufFieldEnum = VaultRequest_QtProtobufNested::QtProtobufFieldEnum;
    VaultRequest();
    ~VaultRequest();
    VaultRequest(const VaultRequest &other);
    VaultRequest &operator =(const VaultRequest &other);
    VaultRequest(VaultRequest &&other) noexcept;
    VaultRequest &operator =(VaultRequest &&other) noexcept
    {
        swap(other);
        return *this;
    }
    void swap(VaultRequest &other) noexcept
    {
        QProtobufMessage::swap(other);
        dptr.swap(other.dptr);
    }
    Q_IMPLICIT operator QVariant() const;

    const QString &token() const &;

    const QString &localPath() const &;
    void setToken(const QString &token);
    void setToken(QString &&token);
    void setLocalPath(const QString &localPath);
    void setLocalPath(QString &&localPath);
    static void registerTypes();

private:
    friend bool comparesEqual(const VaultRequest &lhs, const VaultRequest &rhs) noexcept;
    friend bool operator==(const VaultRequest &lhs, const VaultRequest &rhs) noexcept
    {
        return comparesEqual(lhs, rhs);
    }
    friend bool operator!=(const VaultRequest &lhs, const VaultRequest &rhs) noexcept
    {
        return !comparesEqual(lhs, rhs);
    }
    QExplicitlySharedDataPointer<VaultRequest_QtProtobufData> dptr;
};
namespace VaultRequest_QtProtobufNested {
Q_NAMESPACE

enum class QtProtobufFieldEnum {
    TokenProtoFieldNumber = 1,
    LocalPathProtoFieldNumber = 2,
};
Q_ENUM_NS(QtProtobufFieldEnum)

} // namespace VaultRequest_QtProtobufNested

class VaultQuery_QtProtobufData;
class VaultQuery : public QProtobufMessage
{
    Q_PROTOBUF_OBJECT
    Q_PROPERTY(QString token READ token WRITE setToken SCRIPTABLE true)

public:
    using QtProtobufFieldEnum = VaultQuery_QtProtobufNested::QtProtobufFieldEnum;
    VaultQuery();
    ~VaultQuery();
    VaultQuery(const VaultQuery &other);
    VaultQuery &operator =(const VaultQuery &other);
    VaultQuery(VaultQuery &&other) noexcept;
    VaultQuery &operator =(VaultQuery &&other) noexcept
    {
        swap(other);
        return *this;
    }
    void swap(VaultQuery &other) noexcept
    {
        QProtobufMessage::swap(other);
        dptr.swap(other.dptr);
    }
    Q_IMPLICIT operator QVariant() const;

    const QString &token() const &;
    void setToken(const QString &token);
    void setToken(QString &&token);
    static void registerTypes();

private:
    friend bool comparesEqual(const VaultQuery &lhs, const VaultQuery &rhs) noexcept;
    friend bool operator==(const VaultQuery &lhs, const VaultQuery &rhs) noexcept
    {
        return comparesEqual(lhs, rhs);
    }
    friend bool operator!=(const VaultQuery &lhs, const VaultQuery &rhs) noexcept
    {
        return !comparesEqual(lhs, rhs);
    }
    QExplicitlySharedDataPointer<VaultQuery_QtProtobufData> dptr;
};
namespace VaultQuery_QtProtobufNested {
Q_NAMESPACE

enum class QtProtobufFieldEnum {
    TokenProtoFieldNumber = 1,
};
Q_ENUM_NS(QtProtobufFieldEnum)

} // namespace VaultQuery_QtProtobufNested

class VaultResponse_QtProtobufData;
class VaultResponse : public QProtobufMessage
{
    Q_PROTOBUF_OBJECT
    Q_PROPERTY(QString localPath READ localPath WRITE setLocalPath SCRIPTABLE true)

public:
    using QtProtobufFieldEnum = VaultResponse_QtProtobufNested::QtProtobufFieldEnum;
    VaultResponse();
    ~VaultResponse();
    VaultResponse(const VaultResponse &other);
    VaultResponse &operator =(const VaultResponse &other);
    VaultResponse(VaultResponse &&other) noexcept;
    VaultResponse &operator =(VaultResponse &&other) noexcept
    {
        swap(other);
        return *this;
    }
    void swap(VaultResponse &other) noexcept
    {
        QProtobufMessage::swap(other);
        dptr.swap(other.dptr);
    }
    Q_IMPLICIT operator QVariant() const;

    const QString &localPath() const &;
    void setLocalPath(const QString &localPath);
    void setLocalPath(QString &&localPath);
    static void registerTypes();

private:
    friend bool comparesEqual(const VaultResponse &lhs, const VaultResponse &rhs) noexcept;
    friend bool operator==(const VaultResponse &lhs, const VaultResponse &rhs) noexcept
    {
        return comparesEqual(lhs, rhs);
    }
    friend bool operator!=(const VaultResponse &lhs, const VaultResponse &rhs) noexcept
    {
        return !comparesEqual(lhs, rhs);
    }
    QExplicitlySharedDataPointer<VaultResponse_QtProtobufData> dptr;
};
namespace VaultResponse_QtProtobufNested {
Q_NAMESPACE

enum class QtProtobufFieldEnum {
    LocalPathProtoFieldNumber = 1,
};
Q_ENUM_NS(QtProtobufFieldEnum)

} // namespace VaultResponse_QtProtobufNested

class FileTransferPath_QtProtobufData;
class FileTransferPath : public QProtobufMessage
{
    Q_PROTOBUF_OBJECT
    Q_PROPERTY(QString token READ token WRITE setToken SCRIPTABLE true)
    Q_PROPERTY(QString remoteName READ remoteName WRITE setRemoteName SCRIPTABLE true)
    Q_PROPERTY(QString localPath READ localPath WRITE setLocalPath SCRIPTABLE true)

public:
    using QtProtobufFieldEnum = FileTransferPath_QtProtobufNested::QtProtobufFieldEnum;
    FileTransferPath();
    ~FileTransferPath();
    FileTransferPath(const FileTransferPath &other);
    FileTransferPath &operator =(const FileTransferPath &other);
    FileTransferPath(FileTransferPath &&other) noexcept;
    FileTransferPath &operator =(FileTransferPath &&other) noexcept
    {
        swap(other);
        return *this;
    }
    void swap(FileTransferPath &other) noexcept
    {
        QProtobufMessage::swap(other);
        dptr.swap(other.dptr);
    }
    Q_IMPLICIT operator QVariant() const;

    const QString &token() const &;

    const QString &remoteName() const &;

    const QString &localPath() const &;
    void setToken(const QString &token);
    void setToken(QString &&token);
    void setRemoteName(const QString &remoteName);
    void setRemoteName(QString &&remoteName);
    void setLocalPath(const QString &localPath);
    void setLocalPath(QString &&localPath);
    static void registerTypes();

private:
    friend bool comparesEqual(const FileTransferPath &lhs, const FileTransferPath &rhs) noexcept;
    friend bool operator==(const FileTransferPath &lhs, const FileTransferPath &rhs) noexcept
    {
        return comparesEqual(lhs, rhs);
    }
    friend bool operator!=(const FileTransferPath &lhs, const FileTransferPath &rhs) noexcept
    {
        return !comparesEqual(lhs, rhs);
    }
    QExplicitlySharedDataPointer<FileTransferPath_QtProtobufData> dptr;
};
namespace FileTransferPath_QtProtobufNested {
Q_NAMESPACE

enum class QtProtobufFieldEnum {
    TokenProtoFieldNumber = 1,
    RemoteNameProtoFieldNumber = 2,
    LocalPathProtoFieldNumber = 3,
};
Q_ENUM_NS(QtProtobufFieldEnum)

} // namespace FileTransferPath_QtProtobufNested

class GlobalStats_QtProtobufData;
class GlobalStats : public QProtobufMessage
{
    Q_PROTOBUF_OBJECT
    Q_PROPERTY(QtProtobuf::int64 total READ total WRITE setTotal SCRIPTABLE false)
    Q_PROPERTY(QtProtobuf::int64 free READ free WRITE setFree SCRIPTABLE false)

public:
    using QtProtobufFieldEnum = GlobalStats_QtProtobufNested::QtProtobufFieldEnum;
    GlobalStats();
    ~GlobalStats();
    GlobalStats(const GlobalStats &other);
    GlobalStats &operator =(const GlobalStats &other);
    GlobalStats(GlobalStats &&other) noexcept;
    GlobalStats &operator =(GlobalStats &&other) noexcept
    {
        swap(other);
        return *this;
    }
    void swap(GlobalStats &other) noexcept
    {
        QProtobufMessage::swap(other);
        dptr.swap(other.dptr);
    }
    Q_IMPLICIT operator QVariant() const;

    QtProtobuf::int64 total() const;

    QtProtobuf::int64 free() const;
    void setTotal(QtProtobuf::int64 total);
    void setFree(QtProtobuf::int64 free);
    static void registerTypes();

private:
    friend bool comparesEqual(const GlobalStats &lhs, const GlobalStats &rhs) noexcept;
    friend bool operator==(const GlobalStats &lhs, const GlobalStats &rhs) noexcept
    {
        return comparesEqual(lhs, rhs);
    }
    friend bool operator!=(const GlobalStats &lhs, const GlobalStats &rhs) noexcept
    {
        return !comparesEqual(lhs, rhs);
    }
    QExplicitlySharedDataPointer<GlobalStats_QtProtobufData> dptr;
};
namespace GlobalStats_QtProtobufNested {
Q_NAMESPACE

enum class QtProtobufFieldEnum {
    TotalProtoFieldNumber = 1,
    FreeProtoFieldNumber = 2,
};
Q_ENUM_NS(QtProtobufFieldEnum)

} // namespace GlobalStats_QtProtobufNested

class Status_QtProtobufData;
class Status : public QProtobufMessage
{
    Q_PROTOBUF_OBJECT
    Q_PROPERTY(bool success READ success WRITE setSuccess SCRIPTABLE true)
    Q_PROPERTY(QString message READ message WRITE setMessage SCRIPTABLE true)

public:
    using QtProtobufFieldEnum = Status_QtProtobufNested::QtProtobufFieldEnum;
    Status();
    ~Status();
    Status(const Status &other);
    Status &operator =(const Status &other);
    Status(Status &&other) noexcept;
    Status &operator =(Status &&other) noexcept
    {
        swap(other);
        return *this;
    }
    void swap(Status &other) noexcept
    {
        QProtobufMessage::swap(other);
        dptr.swap(other.dptr);
    }
    Q_IMPLICIT operator QVariant() const;

    bool success() const;

    const QString &message() const &;
    void setSuccess(bool success);
    void setMessage(const QString &message);
    void setMessage(QString &&message);
    static void registerTypes();

private:
    friend bool comparesEqual(const Status &lhs, const Status &rhs) noexcept;
    friend bool operator==(const Status &lhs, const Status &rhs) noexcept
    {
        return comparesEqual(lhs, rhs);
    }
    friend bool operator!=(const Status &lhs, const Status &rhs) noexcept
    {
        return !comparesEqual(lhs, rhs);
    }
    QExplicitlySharedDataPointer<Status_QtProtobufData> dptr;
};
namespace Status_QtProtobufNested {
Q_NAMESPACE

enum class QtProtobufFieldEnum {
    SuccessProtoFieldNumber = 1,
    MessageProtoFieldNumber = 2,
};
Q_ENUM_NS(QtProtobufFieldEnum)

} // namespace Status_QtProtobufNested
} // namespace cloudseal::grpc

#endif // CLOUDSEAL_QPB_H
