name: UserService CI (Dev)

on:
  push:
    branches: [ dev ]
    paths:
      - 'CloudSealAPI/UserService/**'
      - 'CloudSealAPI/UserService.Tests/**'
      - '.github/workflows/user-ci-dev.yml'
  pull_request:
    branches: [ master, dev ]
    paths:
      - 'CloudSealAPI/UserService/**'
      - 'CloudSealAPI/UserService.Tests/**'
      - '.github/workflows/user-ci-dev.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Unit Tests (Only)

    defaults:
      run:
        working-directory: CloudSealAPI

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore UserService.Tests/UserService.Tests.csproj

      - name: Build project
        run: dotnet build UserService.Tests/UserService.Tests.csproj --no-restore

      - name: Run unit tests
        run: dotnet test UserService.Tests/UserService.Tests.csproj --no-build --verbosity normal
